// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcHzSASsOYsb8XwAB1mUR-kZmcLIgypog',
    appId: '1:1051290775734:web:d2293001306b3304473617',
    messagingSenderId: '1051290775734',
    projectId: 'shilpsetu-c13cd',
    authDomain: 'shilpsetu-c13cd.firebaseapp.com',
    storageBucket: 'shilpsetu-c13cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU8DBgwBPtsxrj4TG9tFyfc9HvsQiOUYY',
    appId: '1:1051290775734:android:6e88c2c224d7e8ca473617',
    messagingSenderId: '1051290775734',
    projectId: 'shilpsetu-c13cd',
    storageBucket: 'shilpsetu-c13cd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApMV48vIK4azvieDxUigaZS0WuxLSSvvs',
    appId: '1:1051290775734:ios:0d0f9ad3a248e74e473617',
    messagingSenderId: '1051290775734',
    projectId: 'shilpsetu-c13cd',
    storageBucket: 'shilpsetu-c13cd.firebasestorage.app',
    iosBundleId: 'com.example.shilpsetu',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApMV48vIK4azvieDxUigaZS0WuxLSSvvs',
    appId: '1:1051290775734:ios:0d0f9ad3a248e74e473617',
    messagingSenderId: '1051290775734',
    projectId: 'shilpsetu-c13cd',
    storageBucket: 'shilpsetu-c13cd.firebasestorage.app',
    iosBundleId: 'com.example.shilpsetu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcHzSASsOYsb8XwAB1mUR-kZmcLIgypog',
    appId: '1:1051290775734:web:f33d14a1f9641199473617',
    messagingSenderId: '1051290775734',
    projectId: 'shilpsetu-c13cd',
    authDomain: 'shilpsetu-c13cd.firebaseapp.com',
    storageBucket: 'shilpsetu-c13cd.firebasestorage.app',
  );
}
